# permissions for end users to edit serves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serve-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: llmaz-operator
    app.kubernetes.io/part-of: llmaz-operator
    app.kubernetes.io/managed-by: kustomize
  name: serve-editor-role
rules:
- apiGroups:
  - llmaz.inftyai.io
  resources:
  - serves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llmaz.inftyai.io
  resources:
  - serves/status
  verbs:
  - get
