apiVersion: llmaz.inftyai.io/v1alpha1
kind: Serve
metadata:
  labels:
    app.kubernetes.io/name: serve
    app.kubernetes.io/instance: serve-sample
    app.kubernetes.io/part-of: llmaz-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: llmaz-operator
  name: serve-sample
spec:
  # TODO(user): Add fields here
  modelNameOrPath: test
  replicas: 5
  minReplicas: 1
  maxReplicas: 10
  backend: huggingface
  template:
    containers:
      - name: serve # DO NOT change this
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
